<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

	<ItemGroup>
		<Content Include="Assets\**\*.*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

  <ItemGroup>
    <None Remove="Views\archivo.png" />
    <None Remove="Views\asistente-virtual.png" />
    <None Remove="Views\borrador.png" />
    <None Remove="Views\cerebro.png" />
    <None Remove="Views\cine.png" />
    <None Remove="Views\control.png" />
    <None Remove="Views\deporte.png" />
    <None Remove="Views\desplazarse.png" />
    <None Remove="Views\Fondo.png" />
    <None Remove="Views\geografia.png" />
    <None Remove="Views\globo.png" />
    <None Remove="Views\Musica.png" />
    <None Remove="Views\nota-musical.png" />
    <None Remove="Views\puntuacion-mas-alta.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MySql.Data" Version="9.6.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Views\archivo.png" />
    <Resource Include="Views\asistente-virtual.png" />
    <Resource Include="Views\borrador.png" />
    <Resource Include="Views\cerebro.png" />
    <Resource Include="Views\cine.png" />
    <Resource Include="Views\control.png" />
    <Resource Include="Views\deporte.png" />
    <Resource Include="Views\desplazarse.png" />
    <Resource Include="Views\Fondo.png" />
    <Resource Include="Views\geografia.png" />
    <Resource Include="Views\globo.png" />
    <Resource Include="Views\Musica.png" />
    <Resource Include="Views\nota-musical.png" />
    <Resource Include="Views\puntuacion-mas-alta.png" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Assets\Audios\Cultura general\Pregunta 1\" />
    <Folder Include="Assets\Audios\Cultura general\Pregunta 2\" />
    <Folder Include="Assets\Audios\Cultura general\Pregunta 3\" />
    <Folder Include="Assets\Audios\Cultura general\Pregunta 4\" />
    <Folder Include="Assets\Audios\Deportes\Pregunta 1\" />
    <Folder Include="Assets\Audios\Deportes\Pregunta 2\" />
    <Folder Include="Assets\Audios\Deportes\Pregunta 3\" />
    <Folder Include="Assets\Audios\Deportes\Pregunta 4\" />
    <Folder Include="Assets\Audios\Entretenimiento\Pregunta 1\" />
    <Folder Include="Assets\Audios\Entretenimiento\Pregunta 3\" />
    <Folder Include="Assets\Audios\Entretenimiento\Pregunta 4\" />
    <Folder Include="Assets\Audios\Geografia\Pregunta 1\" />
    <Folder Include="Assets\Audios\Geografia\Pregunta 2\" />
    <Folder Include="Assets\Audios\Geografia\Pregunta 3\" />
    <Folder Include="Assets\Audios\Geografia\Pregunta 4\" />
    <Folder Include="Assets\Audios\Historia\Pregunta 1\" />
    <Folder Include="Assets\Audios\Historia\Pregunta 2\" />
    <Folder Include="Assets\Audios\Historia\Pregunta 3\" />
    <Folder Include="Assets\Audios\Historia\Pregunta 4\" />
    <Folder Include="Assets\Audios\Musica\Pregunta 1\" />
    <Folder Include="Assets\Audios\Musica\Pregunta 3\" />
    <Folder Include="Assets\Audios\Musica\Pregunta 4\" />
    <Folder Include="Assets\Audios\Videojuegos\Pregunta 1\" />
    <Folder Include="Assets\Audios\Videojuegos\Pregunta 2\" />
    <Folder Include="Assets\Audios\Videojuegos\Pregunta 3\" />
    <Folder Include="Assets\Audios\Videojuegos\Pregunta 4\" />
  </ItemGroup>
	

</Project>
